"""Fixed book copy per language (brand name always comes from config)."""

STRINGS: dict[str, dict[str, str]] = {
    "ar": {
        "keepsake_title": "وَهٰكَذا وُلِدَ صاحِبي",
        "drawing_label": "رَسْمَتي",
        "companion_label": "{companion} في الحِكايَة",
        "keepsake_note": "رَسَمَهُ {name} بِيَدَيْهِ… وَصارَ بَطَلًا في حِكايَتِهِ.",
        "keepsake_note_f": "رَسَمَتْهُ {name} بِيَدَيْها… وَصارَ بَطَلًا في حِكايَتِها.",
        "watermark": "مُعايَنَة · {brand}",
        "dedication_label": "إهْداء",
        "made_for": "حِكايَةٌ كُتِبَتْ وَرُسِمَتْ خِصّيصًا لِـ{name}",
        "the_end": "النِّهايَة",
        "parents_title": "لِلأَهْل",
        "parents_lesson_label": "ماذا تُعَلِّمُ هذِهِ الحِكايَة؟",
        "parents_questions_label": "سُؤالانِ بَعْدَ القِراءَة",
        "activity_title_m": "ارْسُمْ أَجْمَلَ لَحْظَةٍ في حِكايَتِك",
        "activity_title_f": "ارْسُمي أَجْمَلَ لَحْظَةٍ في حِكايَتِكِ",
        "memories_title": "ذِكْرَياتُنا",
        "memories_photo": "صورَةٌ مِنْ هذا اليَوْم",
        "back_voice": "امْسَحوا الرَّمْزَ لِتَسْمَعوا الحِكايَةَ بِصَوْتِ العائِلَة",
        "back_voice_soon": "قَريبًا: الحِكايَةُ بِصَوْتِ العائِلَة",
        "made_by": "صُنِعَ بِحُبٍّ في {brand}",
    },
    "en": {
        "keepsake_title": "And that's how my friend was born",
        "drawing_label": "My drawing",
        "companion_label": "{companion} in the story",
        "keepsake_note": "Drawn by {name}'s own hands… now a hero in the story.",
        "keepsake_note_f": "Drawn by {name}'s own hands… now a hero in the story.",
        "watermark": "Preview · {brand}",
        "dedication_label": "Dedication",
        "made_for": "A story written and illustrated especially for {name}",
        "the_end": "The End",
        "parents_title": "For parents",
        "parents_lesson_label": "What this story teaches",
        "parents_questions_label": "Two questions after reading",
        "activity_title_m": "Draw your favorite moment from the story",
        "activity_title_f": "Draw your favorite moment from the story",
        "memories_title": "Our memories",
        "memories_photo": "A photo from this day",
        "back_voice": "Scan to hear the story in your family's voice",
        "back_voice_soon": "Coming soon: the story in your family's voice",
        "made_by": "Made with love by {brand}",
    },
}
