"""free covers

Revision ID: 2a1032d34933
Revises: 7b04ca0efdb2
Create Date: 2026-09-29 09:41:21.568185
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "2a1032d34933"
down_revision: str | None = "7b04ca0efdb2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "free_covers",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("child_id", sa.Uuid(), nullable=False),
        sa.Column("theme_id", sa.Uuid(), nullable=False),
        sa.Column("template_id", sa.Uuid(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "drawing",
                "ready",
                "failed",
                name="free_cover_status",
                native_enum=False,
                create_constraint=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("lang", sa.String(length=2), nullable=False),
        sa.Column("image_key", sa.String(length=300), nullable=True),
        sa.Column("story_key", sa.String(length=300), nullable=True),
        sa.Column("reference", sa.String(length=16), nullable=True),
        sa.Column("cost_usd", sa.Numeric(precision=10, scale=4), nullable=False),
        sa.Column("qa", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "status IN ('drawing', 'ready', 'failed')", name=op.f("ck_free_covers_free_cover_status")
        ),
        sa.ForeignKeyConstraint(
            ["child_id"], ["children.id"], name=op.f("fk_free_covers_child_id_children"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["template_id"],
            ["classic_templates.id"],
            name=op.f("fk_free_covers_template_id_classic_templates"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["theme_id"], ["themes.id"], name=op.f("fk_free_covers_theme_id_themes"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_free_covers_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_free_covers")),
        sa.UniqueConstraint("user_id", "theme_id", name=op.f("uq_free_covers_user_id_theme_id")),
    )
    op.create_index(op.f("ix_free_covers_child_id"), "free_covers", ["child_id"], unique=False)
    op.create_index(op.f("ix_free_covers_user_id"), "free_covers", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_free_covers_user_id"), table_name="free_covers")
    op.drop_index(op.f("ix_free_covers_child_id"), table_name="free_covers")
    op.drop_table("free_covers")
    # ### end Alembic commands ###
