"""classic templates and identity portraits

Revision ID: 7b04ca0efdb2
Revises: 466ebc924be6
Create Date: 2026-09-29 08:59:56.166905
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "7b04ca0efdb2"
down_revision: str | None = "466ebc924be6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "child_portraits",
        sa.Column("child_id", sa.Uuid(), nullable=False),
        sa.Column("art_style", sa.String(length=40), nullable=False),
        sa.Column("image_key", sa.String(length=300), nullable=False),
        sa.Column("source", sa.String(length=16), nullable=False),
        sa.Column("provider", sa.String(length=32), nullable=True),
        sa.Column("model", sa.String(length=100), nullable=True),
        sa.Column("params", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["child_id"],
            ["children.id"],
            name=op.f("fk_child_portraits_child_id_children"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_child_portraits")),
        sa.UniqueConstraint("child_id", "art_style", name=op.f("uq_child_portraits_child_id_art_style")),
    )
    op.create_index(op.f("ix_child_portraits_child_id"), "child_portraits", ["child_id"], unique=False)
    op.create_table(
        "classic_templates",
        sa.Column("theme_id", sa.Uuid(), nullable=False),
        sa.Column("theme_version", sa.Integer(), nullable=False),
        sa.Column("art_style", sa.String(length=40), nullable=False),
        sa.Column("variant", sa.String(length=40), nullable=False),
        sa.Column("lang", sa.String(length=2), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "draft",
                "in_review",
                "approved",
                "live",
                name="classic_template_status",
                native_enum=False,
                create_constraint=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "job",
            sa.Enum(
                "idle",
                "queued",
                "running",
                "failed",
                name="classic_template_job",
                native_enum=False,
                create_constraint=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("source", sa.String(length=16), nullable=False),
        sa.Column("source_book_id", sa.Uuid(), nullable=True),
        sa.Column("generation", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("cost_usd", sa.Numeric(precision=10, scale=4), nullable=False),
        sa.Column("budget_usd", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("flags", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("created_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("approved_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("live_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "job IN ('idle', 'queued', 'running', 'failed')",
            name=op.f("ck_classic_templates_classic_template_job"),
        ),
        sa.CheckConstraint(
            "status IN ('draft', 'in_review', 'approved', 'live')",
            name=op.f("ck_classic_templates_classic_template_status"),
        ),
        sa.ForeignKeyConstraint(
            ["approved_by_user_id"],
            ["users.id"],
            name=op.f("fk_classic_templates_approved_by_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
            name=op.f("fk_classic_templates_created_by_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["source_book_id"],
            ["books.id"],
            name=op.f("fk_classic_templates_source_book_id_books"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["theme_id"],
            ["themes.id"],
            name=op.f("fk_classic_templates_theme_id_themes"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_classic_templates")),
        sa.UniqueConstraint(
            "theme_id", "art_style", "variant", name=op.f("uq_classic_templates_theme_id_art_style_variant")
        ),
    )
    op.create_index(op.f("ix_classic_templates_theme_id"), "classic_templates", ["theme_id"], unique=False)
    op.create_table(
        "classic_template_pages",
        sa.Column("template_id", sa.Uuid(), nullable=False),
        sa.Column("beat", sa.SmallInteger(), nullable=False),
        sa.Column("layout", sa.String(length=16), nullable=True),
        sa.Column("image_key", sa.String(length=300), nullable=True),
        sa.Column("raw_key", sa.String(length=300), nullable=True),
        sa.Column("preview_key", sa.String(length=300), nullable=True),
        sa.Column("has_hero", sa.Boolean(), nullable=False),
        sa.Column("hero_box", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("text_box", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "ok",
                "needs_review",
                "failed",
                "skipped",
                name="classic_page_status",
                native_enum=False,
                create_constraint=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("qa", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("qa_score", sa.Numeric(precision=4, scale=3), nullable=True),
        sa.Column("attempts", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("flags", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("locked", sa.Boolean(), nullable=False),
        sa.Column("regen_count", sa.SmallInteger(), nullable=False),
        sa.Column("cost_usd", sa.Numeric(precision=10, scale=4), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "status IN ('pending', 'ok', 'needs_review', 'failed', 'skipped')",
            name=op.f("ck_classic_template_pages_classic_page_status"),
        ),
        sa.ForeignKeyConstraint(
            ["template_id"],
            ["classic_templates.id"],
            name=op.f("fk_classic_template_pages_template_id_classic_templates"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_classic_template_pages")),
        sa.UniqueConstraint("template_id", "beat", name=op.f("uq_classic_template_pages_template_id_beat")),
    )
    op.create_index(
        op.f("ix_classic_template_pages_template_id"), "classic_template_pages", ["template_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_classic_template_pages_template_id"), table_name="classic_template_pages")
    op.drop_table("classic_template_pages")
    op.drop_index(op.f("ix_classic_templates_theme_id"), table_name="classic_templates")
    op.drop_table("classic_templates")
    op.drop_index(op.f("ix_child_portraits_child_id"), table_name="child_portraits")
    op.drop_table("child_portraits")
    # ### end Alembic commands ###
