"""phase 2-3 remainder: notifications and print batch fields

Revision ID: 5125d903ce3f
Revises: 2a1032d34933
Create Date: 2026-09-28 22:30:48.405730
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "5125d903ce3f"
down_revision: str | None = "2a1032d34933"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "notifications",
        sa.Column("dedupe_key", sa.String(length=120), nullable=False),
        sa.Column("channel", sa.String(length=16), nullable=False),
        sa.Column("template", sa.String(length=40), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "sent",
                "logged",
                "skipped",
                "failed",
                name="notification_status",
                native_enum=False,
                create_constraint=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column("order_id", sa.Uuid(), nullable=True),
        sa.Column("book_id", sa.Uuid(), nullable=True),
        sa.Column("print_batch_id", sa.Uuid(), nullable=True),
        sa.Column("attempts", sa.SmallInteger(), nullable=False),
        sa.Column("error", sa.String(length=200), nullable=True),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "status IN ('pending', 'sent', 'logged', 'skipped', 'failed')",
            name=op.f("ck_notifications_notification_status"),
        ),
        sa.ForeignKeyConstraint(
            ["book_id"], ["books.id"], name=op.f("fk_notifications_book_id_books"), ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["order_id"], ["orders.id"], name=op.f("fk_notifications_order_id_orders"), ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["print_batch_id"],
            ["print_batches.id"],
            name=op.f("fk_notifications_print_batch_id_print_batches"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_notifications_user_id_users"), ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_notifications")),
        sa.UniqueConstraint("dedupe_key", name=op.f("uq_notifications_dedupe_key")),
    )
    op.create_index(op.f("ix_notifications_order_id"), "notifications", ["order_id"], unique=False)
    op.create_index(op.f("ix_notifications_user_id"), "notifications", ["user_id"], unique=False)
    op.add_column("print_batches", sa.Column("printer_token_hash", sa.String(length=64), nullable=True))
    op.add_column(
        "print_batches", sa.Column("printer_token_expires_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column(
        "print_batches",
        sa.Column(
            "manifest",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
    )
    op.alter_column("print_batches", "manifest", server_default=None)
    op.add_column("print_batches", sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column("print_batches", sa.Column("printing_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column("print_batches", sa.Column("done_at", sa.DateTime(timezone=True), nullable=True))
    op.create_unique_constraint(
        op.f("uq_print_batches_printer_token_hash"), "print_batches", ["printer_token_hash"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("uq_print_batches_printer_token_hash"), "print_batches", type_="unique")
    op.drop_column("print_batches", "done_at")
    op.drop_column("print_batches", "printing_at")
    op.drop_column("print_batches", "sent_at")
    op.drop_column("print_batches", "manifest")
    op.drop_column("print_batches", "printer_token_expires_at")
    op.drop_column("print_batches", "printer_token_hash")
    op.drop_index(op.f("ix_notifications_user_id"), table_name="notifications")
    op.drop_index(op.f("ix_notifications_order_id"), table_name="notifications")
    op.drop_table("notifications")
    # ### end Alembic commands ###
