"""template studio theme versions

Revision ID: 918b650a07fc
Revises: 19ebf7d578eb
Create Date: 2026-09-29 15:07:04.430392
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "918b650a07fc"
down_revision: str | None = "19ebf7d578eb"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "theme_versions",
        sa.Column("theme_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "draft",
                "in_review",
                "approved",
                "live",
                "retired",
                name="theme_version_status",
                native_enum=False,
                create_constraint=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("source", sa.String(length=16), nullable=False),
        sa.Column("base_version", sa.Integer(), nullable=True),
        sa.Column("definition", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("note", sa.String(length=300), nullable=True),
        sa.Column("meta", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("approved_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("published_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "status IN ('draft', 'in_review', 'approved', 'live', 'retired')",
            name=op.f("ck_theme_versions_theme_version_status"),
        ),
        sa.ForeignKeyConstraint(
            ["approved_by_user_id"],
            ["users.id"],
            name=op.f("fk_theme_versions_approved_by_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
            name=op.f("fk_theme_versions_created_by_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["published_by_user_id"],
            ["users.id"],
            name=op.f("fk_theme_versions_published_by_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["theme_id"], ["themes.id"], name=op.f("fk_theme_versions_theme_id_themes"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_theme_versions")),
        sa.UniqueConstraint("theme_id", "version", name=op.f("uq_theme_versions_theme_id_version")),
    )
    op.create_index(op.f("ix_theme_versions_theme_id"), "theme_versions", ["theme_id"], unique=False)
    op.create_index(
        "uq_theme_versions_live",
        "theme_versions",
        ["theme_id"],
        unique=True,
        postgresql_where=sa.text("status = 'live'"),
    )
    op.create_index(
        "uq_theme_versions_open",
        "theme_versions",
        ["theme_id"],
        unique=True,
        postgresql_where=sa.text("status IN ('draft', 'in_review', 'approved')"),
    )
    op.add_column("classic_templates", sa.Column("publish_at", sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###
    # Each theme's current definition becomes the first entry of its history: live, from the content files.
    op.execute(
        "INSERT INTO theme_versions (id, theme_id, version, status, source, definition, meta, created_at, "
        "updated_at, published_at) SELECT gen_random_uuid(), id, version, 'live', 'file', definition, "
        "'{}'::jsonb, now(), now(), now() FROM themes"
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("classic_templates", "publish_at")
    op.drop_index(
        "uq_theme_versions_open",
        table_name="theme_versions",
        postgresql_where=sa.text("status IN ('draft', 'in_review', 'approved')"),
    )
    op.drop_index(
        "uq_theme_versions_live", table_name="theme_versions", postgresql_where=sa.text("status = 'live'")
    )
    op.drop_index(op.f("ix_theme_versions_theme_id"), table_name="theme_versions")
    op.drop_table("theme_versions")
    # ### end Alembic commands ###
