"""journey audio clips

Revision ID: 97b657f5bf00
Revises: 5c7e2f19a4b6
Create Date: 2026-09-29 20:18:01.295944
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "97b657f5bf00"
down_revision: str | None = "5c7e2f19a4b6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audio_clips",
        sa.Column("code", sa.String(length=16), nullable=False),
        sa.Column("product", sa.String(length=32), nullable=False),
        sa.Column("storage_key", sa.String(length=300), nullable=False),
        sa.Column("mime", sa.String(length=40), nullable=False),
        sa.Column("duration_ms", sa.Integer(), nullable=False),
        sa.Column("source", sa.String(length=16), nullable=False),
        sa.Column("uploaded_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["uploaded_by_user_id"],
            ["users.id"],
            name=op.f("fk_audio_clips_uploaded_by_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("code", name=op.f("pk_audio_clips")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("audio_clips")
    # ### end Alembic commands ###
