"""Addendum 4: the store — catalog, art styles, add-ons, pricing rules, shipping, carts, order history,
invoices and staff roles.

Hand-edited: server defaults for the new NOT NULL columns on existing tables; the order statuses of
Addendum 4 §5 (pending → new, in_production → printing); existing admins become owners.

Revision ID: 65d890e21316
Revises: a0e70a023aae
Create Date: 2026-09-28 16:33:47.577580
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

_OLD = ("pending", "confirmed", "in_production", "shipped", "delivered", "cancelled")
_NEW = (
    "new",
    "confirmed",
    "generating",
    "review",
    "printing",
    "shipped",
    "delivered",
    "cancelled",
    "reprint",
)
ORDER_STATUSES_OLD = ", ".join(f"'{v}'" for v in _OLD)
ORDER_STATUSES_NEW = ", ".join(f"'{v}'" for v in _NEW)
EMPTY = sa.text("'{}'::jsonb")

revision: str = "65d890e21316"
down_revision: str | None = "a0e70a023aae"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "addons",
        sa.Column("slug", sa.String(length=64), nullable=False),
        sa.Column("name_ar", sa.String(length=120), nullable=False),
        sa.Column("name_en", sa.String(length=120), nullable=False),
        sa.Column("description_ar", sa.Text(), nullable=False),
        sa.Column("description_en", sa.Text(), nullable=False),
        sa.Column("image", sa.String(length=300), nullable=True),
        sa.Column(
            "pricing",
            sa.Enum(
                "fixed",
                "percent_of_item",
                name="addon_pricing",
                native_enum=False,
                create_constraint=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("percent", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("cost_ils", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("cost_ai_usd", sa.Numeric(precision=10, scale=4), nullable=False),
        sa.Column("lines", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("included_lines", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("requires", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("excludes", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("max_qty", sa.SmallInteger(), nullable=False),
        sa.Column("daily_capacity", sa.Integer(), nullable=True),
        sa.Column("step", sa.String(length=24), nullable=False),
        sa.Column("sort", sa.SmallInteger(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("pricing IN ('fixed', 'percent_of_item')", name=op.f("ck_addons_addon_pricing")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_addons")),
        sa.UniqueConstraint("slug", name=op.f("uq_addons_slug")),
    )
    op.create_table(
        "art_styles",
        sa.Column("slug", sa.String(length=40), nullable=False),
        sa.Column("name_ar", sa.String(length=80), nullable=False),
        sa.Column("name_en", sa.String(length=80), nullable=False),
        sa.Column("description_ar", sa.Text(), nullable=False),
        sa.Column("description_en", sa.Text(), nullable=False),
        sa.Column("prompt", sa.Text(), nullable=False),
        sa.Column("negative", sa.Text(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("lines", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("price_modifier_ils", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("price_modifier_jod", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("cost_modifier_usd", sa.Numeric(precision=10, scale=4), nullable=False),
        sa.Column("qa_threshold", sa.Numeric(precision=4, scale=3), nullable=False),
        sa.Column("likeness_min", sa.SmallInteger(), nullable=False),
        sa.Column("sample_images", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("sort", sa.SmallInteger(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_art_styles")),
        sa.UniqueConstraint("slug", name=op.f("uq_art_styles_slug")),
    )
    op.create_table(
        "bundles",
        sa.Column("slug", sa.String(length=64), nullable=False),
        sa.Column("name_ar", sa.String(length=120), nullable=False),
        sa.Column("name_en", sa.String(length=120), nullable=False),
        sa.Column(
            "kind",
            sa.Enum(
                "min_items",
                "siblings",
                name="bundle_kind",
                native_enum=False,
                create_constraint=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("min_items", sa.SmallInteger(), nullable=False),
        sa.Column("discount_pct", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("lines", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ends_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("kind IN ('min_items', 'siblings')", name=op.f("ck_bundles_bundle_kind")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_bundles")),
        sa.UniqueConstraint("slug", name=op.f("uq_bundles_slug")),
    )
    op.create_table(
        "counters",
        sa.Column("name", sa.String(length=40), nullable=False),
        sa.Column("value", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("name", name=op.f("pk_counters")),
    )
    op.create_table(
        "coupons",
        sa.Column("code", sa.String(length=32), nullable=False),
        sa.Column(
            "kind",
            sa.Enum(
                "percent", "fixed", name="coupon_kind", native_enum=False, create_constraint=False, length=32
            ),
            nullable=False,
        ),
        sa.Column("value", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column(
            "currency",
            sa.Enum(
                "ILS", "JOD", name="coupon_currency", native_enum=False, create_constraint=False, length=32
            ),
            nullable=True,
        ),
        sa.Column("min_subtotal", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("max_uses", sa.Integer(), nullable=True),
        sa.Column("uses", sa.Integer(), nullable=False),
        sa.Column("per_customer", sa.SmallInteger(), nullable=True),
        sa.Column("first_order_only", sa.Boolean(), nullable=False),
        sa.Column("lines", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ends_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("currency IN ('ILS', 'JOD')", name=op.f("ck_coupons_coupon_currency")),
        sa.CheckConstraint("kind IN ('percent', 'fixed')", name=op.f("ck_coupons_coupon_kind")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_coupons")),
        sa.UniqueConstraint("code", name=op.f("uq_coupons_code")),
    )
    op.create_table(
        "products",
        sa.Column("slug", sa.String(length=64), nullable=False),
        sa.Column(
            "line",
            sa.Enum(
                "classic",
                "magic",
                "coloring",
                "workbook",
                "journey",
                name="product_line",
                native_enum=False,
                create_constraint=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "audience",
            sa.Enum(
                "b2c", "b2b", name="product_audience", native_enum=False, create_constraint=False, length=32
            ),
            nullable=False,
        ),
        sa.Column("name_ar", sa.String(length=120), nullable=False),
        sa.Column("name_en", sa.String(length=120), nullable=False),
        sa.Column("description_ar", sa.Text(), nullable=False),
        sa.Column("description_en", sa.Text(), nullable=False),
        sa.Column("option_names", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("min_qty", sa.SmallInteger(), nullable=False),
        sa.Column("features", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("sort", sa.SmallInteger(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("audience IN ('b2c', 'b2b')", name=op.f("ck_products_product_audience")),
        sa.CheckConstraint(
            "line IN ('classic', 'magic', 'coloring', 'workbook', 'journey')",
            name=op.f("ck_products_product_line"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_products")),
        sa.UniqueConstraint("slug", name=op.f("uq_products_slug")),
    )
    op.create_table(
        "sales",
        sa.Column("name_ar", sa.String(length=120), nullable=False),
        sa.Column("name_en", sa.String(length=120), nullable=False),
        sa.Column("discount_pct", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("lines", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("products", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ends_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sales")),
    )
    op.create_table(
        "shipping_zones",
        sa.Column("slug", sa.String(length=64), nullable=False),
        sa.Column("name_ar", sa.String(length=120), nullable=False),
        sa.Column("name_en", sa.String(length=120), nullable=False),
        sa.Column("country", sa.String(length=2), nullable=False),
        sa.Column("cities", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "currency",
            sa.Enum(
                "ILS",
                "JOD",
                name="shipping_zone_currency",
                native_enum=False,
                create_constraint=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("fee", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("free_over", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("cod_fee", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("cost_ils", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("eta_days_min", sa.SmallInteger(), nullable=False),
        sa.Column("eta_days_max", sa.SmallInteger(), nullable=False),
        sa.Column("sort", sa.SmallInteger(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "currency IN ('ILS', 'JOD')", name=op.f("ck_shipping_zones_shipping_zone_currency")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_shipping_zones")),
        sa.UniqueConstraint("slug", name=op.f("uq_shipping_zones_slug")),
    )
    op.create_table(
        "addon_prices",
        sa.Column("addon_id", sa.Uuid(), nullable=False),
        sa.Column(
            "currency",
            sa.Enum(
                "ILS",
                "JOD",
                name="addon_price_currency",
                native_enum=False,
                create_constraint=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("amount", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.CheckConstraint("currency IN ('ILS', 'JOD')", name=op.f("ck_addon_prices_addon_price_currency")),
        sa.ForeignKeyConstraint(
            ["addon_id"], ["addons.id"], name=op.f("fk_addon_prices_addon_id_addons"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("addon_id", "currency", name=op.f("pk_addon_prices")),
    )
    op.create_table(
        "price_lists",
        sa.Column("organization_id", sa.Uuid(), nullable=True),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column(
            "currency",
            sa.Enum(
                "ILS",
                "JOD",
                name="price_list_currency",
                native_enum=False,
                create_constraint=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("valid_from", sa.DateTime(timezone=True), nullable=True),
        sa.Column("valid_to", sa.DateTime(timezone=True), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("currency IN ('ILS', 'JOD')", name=op.f("ck_price_lists_price_list_currency")),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_price_lists_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_price_lists")),
    )
    op.create_index(op.f("ix_price_lists_organization_id"), "price_lists", ["organization_id"], unique=False)
    op.create_table(
        "product_variants",
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column("sku", sa.String(length=64), nullable=False),
        sa.Column("options", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("name_ar", sa.String(length=160), nullable=False),
        sa.Column("name_en", sa.String(length=160), nullable=False),
        sa.Column("cost_print_ils", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("cost_packaging_ils", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("cost_handling_ils", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("cost_ai_usd", sa.Numeric(precision=10, scale=4), nullable=False),
        sa.Column("sort", sa.SmallInteger(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("fk_product_variants_product_id_products"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_product_variants")),
        sa.UniqueConstraint("sku", name=op.f("uq_product_variants_sku")),
    )
    op.create_index(op.f("ix_product_variants_product_id"), "product_variants", ["product_id"], unique=False)
    op.create_table(
        "carts",
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column("organization_id", sa.Uuid(), nullable=True),
        sa.Column(
            "currency",
            sa.Enum(
                "ILS", "JOD", name="cart_currency", native_enum=False, create_constraint=False, length=32
            ),
            nullable=False,
        ),
        sa.Column("coupon_code", sa.String(length=32), nullable=True),
        sa.Column("zone_id", sa.Uuid(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "open",
                "ordered",
                "abandoned",
                name="cart_status",
                native_enum=False,
                create_constraint=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("currency IN ('ILS', 'JOD')", name=op.f("ck_carts_cart_currency")),
        sa.CheckConstraint("status IN ('open', 'ordered', 'abandoned')", name=op.f("ck_carts_cart_status")),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_carts_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_carts_user_id_users"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["zone_id"],
            ["shipping_zones.id"],
            name=op.f("fk_carts_zone_id_shipping_zones"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_carts")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_carts_token_hash")),
    )
    op.create_index(op.f("ix_carts_organization_id"), "carts", ["organization_id"], unique=False)
    op.create_index(op.f("ix_carts_user_id"), "carts", ["user_id"], unique=False)
    op.create_table(
        "price_list_items",
        sa.Column("price_list_id", sa.Uuid(), nullable=False),
        sa.Column("variant_id", sa.Uuid(), nullable=False),
        sa.Column("tiers", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["price_list_id"],
            ["price_lists.id"],
            name=op.f("fk_price_list_items_price_list_id_price_lists"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["variant_id"],
            ["product_variants.id"],
            name=op.f("fk_price_list_items_variant_id_product_variants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_price_list_items")),
    )
    op.create_index(
        op.f("ix_price_list_items_price_list_id"), "price_list_items", ["price_list_id"], unique=False
    )
    op.create_index(op.f("ix_price_list_items_variant_id"), "price_list_items", ["variant_id"], unique=False)
    op.create_table(
        "user_staff_roles",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "role",
            sa.Enum(
                "owner",
                "admin",
                "editor",
                "reviewer",
                "production",
                "support",
                name="staff_role",
                native_enum=False,
                create_constraint=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("granted_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("granted_by", sa.Uuid(), nullable=True),
        sa.CheckConstraint(
            "role IN ('owner', 'admin', 'editor', 'reviewer', 'production', 'support')",
            name=op.f("ck_user_staff_roles_staff_role"),
        ),
        sa.ForeignKeyConstraint(
            ["granted_by"],
            ["users.id"],
            name=op.f("fk_user_staff_roles_granted_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_user_staff_roles_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("user_id", "role", name=op.f("pk_user_staff_roles")),
    )
    op.create_table(
        "variant_prices",
        sa.Column("variant_id", sa.Uuid(), nullable=False),
        sa.Column(
            "currency",
            sa.Enum(
                "ILS",
                "JOD",
                name="variant_price_currency",
                native_enum=False,
                create_constraint=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("amount", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.CheckConstraint(
            "currency IN ('ILS', 'JOD')", name=op.f("ck_variant_prices_variant_price_currency")
        ),
        sa.ForeignKeyConstraint(
            ["variant_id"],
            ["product_variants.id"],
            name=op.f("fk_variant_prices_variant_id_product_variants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("variant_id", "currency", name=op.f("pk_variant_prices")),
    )
    op.create_table(
        "coupon_redemptions",
        sa.Column("coupon_id", sa.Uuid(), nullable=False),
        sa.Column("order_id", sa.Uuid(), nullable=True),
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column("phone", sa.String(length=32), nullable=True),
        sa.Column("amount", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["coupon_id"],
            ["coupons.id"],
            name=op.f("fk_coupon_redemptions_coupon_id_coupons"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
            name=op.f("fk_coupon_redemptions_order_id_orders"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_coupon_redemptions_user_id_users"), ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_coupon_redemptions")),
    )
    op.create_index(
        op.f("ix_coupon_redemptions_coupon_id"), "coupon_redemptions", ["coupon_id"], unique=False
    )
    op.create_index(op.f("ix_coupon_redemptions_order_id"), "coupon_redemptions", ["order_id"], unique=False)
    op.create_index(op.f("ix_coupon_redemptions_phone"), "coupon_redemptions", ["phone"], unique=False)
    op.create_index(op.f("ix_coupon_redemptions_user_id"), "coupon_redemptions", ["user_id"], unique=False)
    op.create_table(
        "invoices",
        sa.Column("order_id", sa.Uuid(), nullable=False),
        sa.Column("number", sa.String(length=24), nullable=False),
        sa.Column("year", sa.SmallInteger(), nullable=False),
        sa.Column("seq", sa.Integer(), nullable=False),
        sa.Column(
            "currency",
            sa.Enum(
                "ILS", "JOD", name="invoice_currency", native_enum=False, create_constraint=False, length=32
            ),
            nullable=False,
        ),
        sa.Column("total", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("pdf_key", sa.String(length=300), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("currency IN ('ILS', 'JOD')", name=op.f("ck_invoices_invoice_currency")),
        sa.ForeignKeyConstraint(
            ["order_id"], ["orders.id"], name=op.f("fk_invoices_order_id_orders"), ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_invoices")),
        sa.UniqueConstraint("number", name=op.f("uq_invoices_number")),
        sa.UniqueConstraint("order_id", name=op.f("uq_invoices_order_id")),
    )
    op.create_table(
        "order_events",
        sa.Column("order_id", sa.Uuid(), nullable=False),
        sa.Column("actor_user_id", sa.Uuid(), nullable=True),
        sa.Column("kind", sa.String(length=24), nullable=False),
        sa.Column(
            "from_status",
            sa.Enum(
                "new",
                "confirmed",
                "generating",
                "review",
                "printing",
                "shipped",
                "delivered",
                "cancelled",
                "reprint",
                name="order_event_from",
                native_enum=False,
                create_constraint=False,
                length=32,
            ),
            nullable=True,
        ),
        sa.Column(
            "to_status",
            sa.Enum(
                "new",
                "confirmed",
                "generating",
                "review",
                "printing",
                "shipped",
                "delivered",
                "cancelled",
                "reprint",
                name="order_event_to",
                native_enum=False,
                create_constraint=False,
                length=32,
            ),
            nullable=True,
        ),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("data", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "from_status IN ('new', 'confirmed', 'generating', 'review', 'printing', 'shipped', 'delivered', 'cancelled', 'reprint')",
            name=op.f("ck_order_events_order_event_from"),
        ),
        sa.CheckConstraint(
            "to_status IN ('new', 'confirmed', 'generating', 'review', 'printing', 'shipped', 'delivered', 'cancelled', 'reprint')",
            name=op.f("ck_order_events_order_event_to"),
        ),
        sa.ForeignKeyConstraint(
            ["actor_user_id"],
            ["users.id"],
            name=op.f("fk_order_events_actor_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["order_id"], ["orders.id"], name=op.f("fk_order_events_order_id_orders"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_order_events")),
    )
    op.create_index(op.f("ix_order_events_order_id"), "order_events", ["order_id"], unique=False)
    op.create_table(
        "cart_items",
        sa.Column("cart_id", sa.Uuid(), nullable=False),
        sa.Column("variant_id", sa.Uuid(), nullable=False),
        sa.Column("style_slug", sa.String(length=40), nullable=True),
        sa.Column("theme_slug", sa.String(length=64), nullable=True),
        sa.Column("qty", sa.SmallInteger(), nullable=False),
        sa.Column("addons", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("personalization", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("child_id", sa.Uuid(), nullable=True),
        sa.Column("book_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["book_id"], ["books.id"], name=op.f("fk_cart_items_book_id_books"), ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["cart_id"], ["carts.id"], name=op.f("fk_cart_items_cart_id_carts"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["child_id"], ["children.id"], name=op.f("fk_cart_items_child_id_children"), ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["variant_id"],
            ["product_variants.id"],
            name=op.f("fk_cart_items_variant_id_product_variants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cart_items")),
    )
    op.create_index(op.f("ix_cart_items_cart_id"), "cart_items", ["cart_id"], unique=False)
    op.add_column("order_items", sa.Column("variant_id", sa.Uuid(), nullable=True))
    op.add_column("order_items", sa.Column("sku", sa.String(length=64), nullable=True))
    op.add_column("order_items", sa.Column("line", sa.String(length=16), nullable=True))
    op.add_column(
        "order_items",
        sa.Column("title", postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default=EMPTY),
    )
    op.add_column("order_items", sa.Column("style_slug", sa.String(length=40), nullable=True))
    op.add_column("order_items", sa.Column("theme_slug", sa.String(length=64), nullable=True))
    op.add_column("order_items", sa.Column("child_id", sa.Uuid(), nullable=True))
    op.add_column(
        "order_items",
        sa.Column(
            "personalization", postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default=EMPTY
        ),
    )
    op.add_column(
        "order_items",
        sa.Column("discount", sa.Numeric(precision=10, scale=2), nullable=False, server_default="0"),
    )
    op.add_column(
        "order_items",
        sa.Column("costs", postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default=EMPTY),
    )
    op.alter_column("order_items", "product", existing_type=sa.VARCHAR(length=32), nullable=True)
    op.create_index(op.f("ix_order_items_variant_id"), "order_items", ["variant_id"], unique=False)
    op.create_foreign_key(
        op.f("fk_order_items_child_id_children"),
        "order_items",
        "children",
        ["child_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        op.f("fk_order_items_variant_id_product_variants"),
        "order_items",
        "product_variants",
        ["variant_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.add_column("orders", sa.Column("phone", sa.String(length=32), nullable=True))
    op.add_column("orders", sa.Column("source", sa.String(length=16), nullable=False, server_default="web"))
    op.add_column("orders", sa.Column("zone_id", sa.Uuid(), nullable=True))
    op.add_column("orders", sa.Column("price_list_id", sa.Uuid(), nullable=True))
    op.add_column("orders", sa.Column("coupon_id", sa.Uuid(), nullable=True))
    op.add_column(
        "orders",
        sa.Column("pricing", postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default=EMPTY),
    )
    op.add_column(
        "orders", sa.Column("cost_ils", sa.Numeric(precision=10, scale=2), nullable=False, server_default="0")
    )
    op.create_index(op.f("ix_orders_phone"), "orders", ["phone"], unique=False)
    op.create_foreign_key(
        op.f("fk_orders_zone_id_shipping_zones"),
        "orders",
        "shipping_zones",
        ["zone_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        op.f("fk_orders_coupon_id_coupons"), "orders", "coupons", ["coupon_id"], ["id"], ondelete="SET NULL"
    )
    op.create_foreign_key(
        op.f("fk_orders_price_list_id_price_lists"),
        "orders",
        "price_lists",
        ["price_list_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###
    op.drop_constraint(op.f("ck_orders_order_status"), "orders", type_="check")
    op.execute("UPDATE orders SET status = 'new' WHERE status = 'pending'")
    op.execute("UPDATE orders SET status = 'printing' WHERE status = 'in_production'")
    op.create_check_constraint(op.f("ck_orders_order_status"), "orders", f"status IN ({ORDER_STATUSES_NEW})")
    op.execute(
        "INSERT INTO user_staff_roles (user_id, role, granted_at) "
        "SELECT id, 'owner', now() FROM users WHERE role = 'admin' ON CONFLICT DO NOTHING"
    )


def downgrade() -> None:
    op.drop_constraint(op.f("ck_orders_order_status"), "orders", type_="check")
    op.execute("UPDATE orders SET status = 'pending' WHERE status = 'new'")
    op.execute("UPDATE orders SET status = 'confirmed' WHERE status IN ('generating', 'review')")
    op.execute("UPDATE orders SET status = 'in_production' WHERE status IN ('printing', 'reprint')")
    op.create_check_constraint(op.f("ck_orders_order_status"), "orders", f"status IN ({ORDER_STATUSES_OLD})")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("fk_orders_price_list_id_price_lists"), "orders", type_="foreignkey")
    op.drop_constraint(op.f("fk_orders_coupon_id_coupons"), "orders", type_="foreignkey")
    op.drop_constraint(op.f("fk_orders_zone_id_shipping_zones"), "orders", type_="foreignkey")
    op.drop_index(op.f("ix_orders_phone"), table_name="orders")
    op.drop_column("orders", "cost_ils")
    op.drop_column("orders", "pricing")
    op.drop_column("orders", "coupon_id")
    op.drop_column("orders", "price_list_id")
    op.drop_column("orders", "zone_id")
    op.drop_column("orders", "source")
    op.drop_column("orders", "phone")
    op.drop_constraint(op.f("fk_order_items_variant_id_product_variants"), "order_items", type_="foreignkey")
    op.drop_constraint(op.f("fk_order_items_child_id_children"), "order_items", type_="foreignkey")
    op.drop_index(op.f("ix_order_items_variant_id"), table_name="order_items")
    op.alter_column("order_items", "product", existing_type=sa.VARCHAR(length=32), nullable=False)
    op.drop_column("order_items", "costs")
    op.drop_column("order_items", "discount")
    op.drop_column("order_items", "personalization")
    op.drop_column("order_items", "child_id")
    op.drop_column("order_items", "theme_slug")
    op.drop_column("order_items", "style_slug")
    op.drop_column("order_items", "title")
    op.drop_column("order_items", "line")
    op.drop_column("order_items", "sku")
    op.drop_column("order_items", "variant_id")
    op.drop_index(op.f("ix_cart_items_cart_id"), table_name="cart_items")
    op.drop_table("cart_items")
    op.drop_index(op.f("ix_order_events_order_id"), table_name="order_events")
    op.drop_table("order_events")
    op.drop_table("invoices")
    op.drop_index(op.f("ix_coupon_redemptions_user_id"), table_name="coupon_redemptions")
    op.drop_index(op.f("ix_coupon_redemptions_phone"), table_name="coupon_redemptions")
    op.drop_index(op.f("ix_coupon_redemptions_order_id"), table_name="coupon_redemptions")
    op.drop_index(op.f("ix_coupon_redemptions_coupon_id"), table_name="coupon_redemptions")
    op.drop_table("coupon_redemptions")
    op.drop_table("variant_prices")
    op.drop_table("user_staff_roles")
    op.drop_index(op.f("ix_price_list_items_variant_id"), table_name="price_list_items")
    op.drop_index(op.f("ix_price_list_items_price_list_id"), table_name="price_list_items")
    op.drop_table("price_list_items")
    op.drop_index(op.f("ix_carts_user_id"), table_name="carts")
    op.drop_index(op.f("ix_carts_organization_id"), table_name="carts")
    op.drop_table("carts")
    op.drop_index(op.f("ix_product_variants_product_id"), table_name="product_variants")
    op.drop_table("product_variants")
    op.drop_index(op.f("ix_price_lists_organization_id"), table_name="price_lists")
    op.drop_table("price_lists")
    op.drop_table("addon_prices")
    op.drop_table("shipping_zones")
    op.drop_table("sales")
    op.drop_table("products")
    op.drop_table("coupons")
    op.drop_table("counters")
    op.drop_table("bundles")
    op.drop_table("art_styles")
    op.drop_table("addons")
    # ### end Alembic commands ###
