"""phase 4 kindergarten portal

Revision ID: e6b4b0230d6a
Revises: 5125d903ce3f
Create Date: 2026-09-28 22:31:18.739206
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "e6b4b0230d6a"
down_revision: str | None = "5125d903ce3f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "child_invites",
        sa.Column("child_id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("classroom_id", sa.Uuid(), nullable=False),
        sa.Column("token", sa.String(length=64), nullable=False),
        sa.Column("parent_name", sa.String(length=120), nullable=True),
        sa.Column("parent_phone", sa.String(length=32), nullable=True),
        sa.Column("parent_email", sa.String(length=254), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("claimed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("claimed_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["child_id"], ["children.id"], name=op.f("fk_child_invites_child_id_children"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["claimed_by_user_id"],
            ["users.id"],
            name=op.f("fk_child_invites_claimed_by_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["classroom_id"],
            ["classrooms.id"],
            name=op.f("fk_child_invites_classroom_id_classrooms"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_child_invites_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_child_invites")),
        sa.UniqueConstraint("token", name=op.f("uq_child_invites_token")),
    )
    op.create_index(op.f("ix_child_invites_child_id"), "child_invites", ["child_id"], unique=True)
    op.create_index(op.f("ix_child_invites_classroom_id"), "child_invites", ["classroom_id"], unique=False)
    op.create_index(
        op.f("ix_child_invites_organization_id"), "child_invites", ["organization_id"], unique=False
    )
    op.create_table(
        "class_books",
        sa.Column("classroom_id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("theme_id", sa.Uuid(), nullable=True),
        sa.Column("line", sa.String(length=16), nullable=False),
        sa.Column("art_style", sa.String(length=40), nullable=False),
        sa.Column("language", sa.String(length=2), nullable=False),
        sa.Column("min_appearances", sa.SmallInteger(), nullable=False),
        sa.Column("teacher_message", sa.Text(), nullable=True),
        sa.Column("class_photo_key", sa.String(length=300), nullable=True),
        sa.Column("class_photo_consent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("class_photo_consent_by", sa.Uuid(), nullable=True),
        sa.Column("options", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "setup",
                "generating",
                "review",
                "approved",
                "ordered",
                "printing",
                "failed",
                name="class_book_status",
                native_enum=False,
                create_constraint=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("plan", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("progress", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("generation", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("cost_usd", sa.Numeric(precision=10, scale=4), nullable=False),
        sa.Column("flags", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("school_approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("school_approved_by", sa.Uuid(), nullable=True),
        sa.Column("order_id", sa.Uuid(), nullable=True),
        sa.Column("print_batch_id", sa.Uuid(), nullable=True),
        sa.Column("bundle", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "status IN ('setup', 'generating', 'review', 'approved', 'ordered', 'printing', 'failed')",
            name=op.f("ck_class_books_class_book_status"),
        ),
        sa.ForeignKeyConstraint(
            ["class_photo_consent_by"],
            ["users.id"],
            name=op.f("fk_class_books_class_photo_consent_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["classroom_id"],
            ["classrooms.id"],
            name=op.f("fk_class_books_classroom_id_classrooms"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["order_id"], ["orders.id"], name=op.f("fk_class_books_order_id_orders"), ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_class_books_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["print_batch_id"],
            ["print_batches.id"],
            name=op.f("fk_class_books_print_batch_id_print_batches"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["school_approved_by"],
            ["users.id"],
            name=op.f("fk_class_books_school_approved_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["theme_id"], ["themes.id"], name=op.f("fk_class_books_theme_id_themes"), ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_class_books")),
    )
    op.create_index(op.f("ix_class_books_classroom_id"), "class_books", ["classroom_id"], unique=True)
    op.create_index(op.f("ix_class_books_organization_id"), "class_books", ["organization_id"], unique=False)
    op.create_table(
        "class_book_pages",
        sa.Column("class_book_id", sa.Uuid(), nullable=False),
        sa.Column("index", sa.SmallInteger(), nullable=False),
        sa.Column("scene_key", sa.String(length=64), nullable=False),
        sa.Column("child_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("text", sa.Text(), nullable=True),
        sa.Column("image_key", sa.String(length=300), nullable=True),
        sa.Column("print_image_key", sa.String(length=300), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "ok",
                "needs_review",
                "failed",
                "skipped",
                name="class_page_status",
                native_enum=False,
                create_constraint=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("qa", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("flags", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("attempts", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("redraw", sa.Boolean(), nullable=False),
        sa.Column("cost_usd", sa.Numeric(precision=10, scale=4), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "status IN ('pending', 'ok', 'needs_review', 'failed', 'skipped')",
            name=op.f("ck_class_book_pages_class_page_status"),
        ),
        sa.ForeignKeyConstraint(
            ["class_book_id"],
            ["class_books.id"],
            name=op.f("fk_class_book_pages_class_book_id_class_books"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_class_book_pages")),
        sa.UniqueConstraint("class_book_id", "index", name=op.f("uq_class_book_pages_class_book_id_index")),
    )
    op.create_index(
        op.f("ix_class_book_pages_class_book_id"), "class_book_pages", ["class_book_id"], unique=False
    )
    op.add_column("organizations", sa.Column("address", sa.String(length=300), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("organizations", "address")
    op.drop_index(op.f("ix_class_book_pages_class_book_id"), table_name="class_book_pages")
    op.drop_table("class_book_pages")
    op.drop_index(op.f("ix_class_books_organization_id"), table_name="class_books")
    op.drop_index(op.f("ix_class_books_classroom_id"), table_name="class_books")
    op.drop_table("class_books")
    op.drop_index(op.f("ix_child_invites_organization_id"), table_name="child_invites")
    op.drop_index(op.f("ix_child_invites_classroom_id"), table_name="child_invites")
    op.drop_index(op.f("ix_child_invites_child_id"), table_name="child_invites")
    op.drop_table("child_invites")
    # ### end Alembic commands ###
