"""Addendum 3: page QA + review fields, book costs/flags/preflight, hijab/glasses, admin 2FA.

Hand-edited: server defaults so existing rows get values, CHECK constraints for the new page status and
the extended book status, and the admin-settings rename "FLUX model" → "fal fallback model".

Revision ID: a0e70a023aae
Revises: 16e62bfa0dbc
Create Date: 2026-09-28 13:21:55.406713
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "a0e70a023aae"
down_revision: str | None = "16e62bfa0dbc"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

_OLD = ("draft", "generating", "preview", "approved", "ordered", "printed", "failed")
_NEW = ("draft", "generating", "preview", "in_review", "approved", "ordered", "printed", "failed")
BOOK_STATUSES_OLD = ", ".join(f"'{v}'" for v in _OLD)
BOOK_STATUSES_NEW = ", ".join(f"'{v}'" for v in _NEW)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("book_pages", sa.Column("preview_image_key", sa.String(length=300), nullable=True))
    op.add_column("book_pages", sa.Column("layout", sa.String(length=16), nullable=True))
    op.add_column(
        "book_pages",
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "ok",
                "needs_review",
                "failed",
                "skipped",
                name="page_status",
                native_enum=False,
                create_constraint=False,
                length=32,
            ),
            nullable=False,
            server_default="pending",
        ),
    )
    op.add_column(
        "book_pages",
        sa.Column(
            "qa",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            server_default=sa.text("'{}'::jsonb"),
        ),
    )
    op.add_column("book_pages", sa.Column("qa_score", sa.Numeric(precision=4, scale=3), nullable=True))
    op.add_column(
        "book_pages",
        sa.Column(
            "attempts",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            server_default=sa.text("'[]'::jsonb"),
        ),
    )
    op.add_column(
        "book_pages",
        sa.Column(
            "flags",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            server_default=sa.text("'[]'::jsonb"),
        ),
    )
    op.add_column(
        "book_pages",
        sa.Column("cost_usd", sa.Numeric(precision=10, scale=4), nullable=False, server_default="0"),
    )
    op.add_column("books", sa.Column("proof_pdf_key", sa.String(length=300), nullable=True))
    op.add_column("books", sa.Column("parent_message", sa.String(length=120), nullable=True))
    op.add_column("books", sa.Column("is_sample", sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column(
        "books",
        sa.Column(
            "generation",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            server_default=sa.text("'{}'::jsonb"),
        ),
    )
    op.add_column(
        "books",
        sa.Column(
            "story",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            server_default=sa.text("'{}'::jsonb"),
        ),
    )
    op.add_column(
        "books", sa.Column("cost_usd", sa.Numeric(precision=10, scale=4), nullable=False, server_default="0")
    )
    op.add_column("books", sa.Column("budget_usd", sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column(
        "books",
        sa.Column(
            "flags",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            server_default=sa.text("'[]'::jsonb"),
        ),
    )
    op.add_column(
        "books",
        sa.Column(
            "qa_summary",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            server_default=sa.text("'{}'::jsonb"),
        ),
    )
    op.add_column(
        "books",
        sa.Column(
            "preflight",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            server_default=sa.text("'{}'::jsonb"),
        ),
    )
    op.add_column("books", sa.Column("error", sa.Text(), nullable=True))
    op.add_column(
        "children", sa.Column("wears_hijab", sa.Boolean(), nullable=False, server_default=sa.false())
    )
    op.add_column(
        "children", sa.Column("wears_glasses", sa.Boolean(), nullable=False, server_default=sa.false())
    )
    op.add_column("children", sa.Column("is_sample", sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column("refresh_tokens", sa.Column("mfa", sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column("users", sa.Column("totp_secret_ciphertext", sa.Text(), nullable=True))
    op.add_column("users", sa.Column("totp_enabled_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column("users", sa.Column("totp_last_step", sa.BigInteger(), nullable=True))
    op.add_column(
        "users",
        sa.Column(
            "recovery_codes",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            server_default=sa.text("'[]'::jsonb"),
        ),
    )
    # ### end Alembic commands ###
    op.create_check_constraint(
        op.f("ck_book_pages_page_status"),
        "book_pages",
        "status IN ('pending', 'ok', 'needs_review', 'failed', 'skipped')",
    )
    op.drop_constraint(op.f("ck_books_book_status"), "books", type_="check")
    op.create_check_constraint(op.f("ck_books_book_status"), "books", f"status IN ({BOOK_STATUSES_NEW})")
    # Admin settings: "FLUX model" became the generic "fal fallback model"; the "flux" provider became "fal".
    op.execute(
        "UPDATE app_settings SET key = 'fal_fallback_model' WHERE key = 'flux_image_model' "
        "AND NOT EXISTS (SELECT 1 FROM app_settings WHERE key = 'fal_fallback_model')"
    )
    op.execute(
        """UPDATE app_settings SET value = '"fal"'::jsonb WHERE key = 'image_provider' AND value = '"flux"'::jsonb"""
    )


def downgrade() -> None:
    op.execute("UPDATE books SET status = 'preview' WHERE status = 'in_review'")
    op.drop_constraint(op.f("ck_books_book_status"), "books", type_="check")
    op.create_check_constraint(op.f("ck_books_book_status"), "books", f"status IN ({BOOK_STATUSES_OLD})")
    op.drop_constraint(op.f("ck_book_pages_page_status"), "book_pages", type_="check")
    op.execute("UPDATE app_settings SET key = 'flux_image_model' WHERE key = 'fal_fallback_model'")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "recovery_codes")
    op.drop_column("users", "totp_last_step")
    op.drop_column("users", "totp_enabled_at")
    op.drop_column("users", "totp_secret_ciphertext")
    op.drop_column("refresh_tokens", "mfa")
    op.drop_column("children", "is_sample")
    op.drop_column("children", "wears_glasses")
    op.drop_column("children", "wears_hijab")
    op.drop_column("books", "error")
    op.drop_column("books", "preflight")
    op.drop_column("books", "qa_summary")
    op.drop_column("books", "flags")
    op.drop_column("books", "budget_usd")
    op.drop_column("books", "cost_usd")
    op.drop_column("books", "story")
    op.drop_column("books", "generation")
    op.drop_column("books", "is_sample")
    op.drop_column("books", "parent_message")
    op.drop_column("books", "proof_pdf_key")
    op.drop_column("book_pages", "cost_usd")
    op.drop_column("book_pages", "flags")
    op.drop_column("book_pages", "attempts")
    op.drop_column("book_pages", "qa_score")
    op.drop_column("book_pages", "qa")
    op.drop_column("book_pages", "status")
    op.drop_column("book_pages", "layout")
    op.drop_column("book_pages", "preview_image_key")
    # ### end Alembic commands ###
