"""add leads

Revision ID: 98d06fef4e4d
Revises: a3a33278ac8b
Create Date: 2026-09-28 10:09:51.068508
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "98d06fef4e4d"
down_revision: str | None = "a3a33278ac8b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "leads",
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("org_name", sa.String(length=200), nullable=False),
        sa.Column("city", sa.String(length=100), nullable=True),
        sa.Column("contact_name", sa.String(length=120), nullable=False),
        sa.Column("contact_role", sa.String(length=120), nullable=True),
        sa.Column("phone", sa.String(length=32), nullable=False),
        sa.Column("children_count", sa.SmallInteger(), nullable=True),
        sa.Column("event_date", sa.Date(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "locale",
            sa.Enum("ar", "en", name="lead_locale", native_enum=False, create_constraint=False, length=32),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "new",
                "contacted",
                "won",
                "lost",
                name="lead_status",
                native_enum=False,
                create_constraint=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("locale IN ('ar', 'en')", name=op.f("ck_leads_lead_locale")),
        sa.CheckConstraint(
            "status IN ('new', 'contacted', 'won', 'lost')", name=op.f("ck_leads_lead_status")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_leads")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("leads")
    # ### end Alembic commands ###
