"""initial schema

Revision ID: a3a33278ac8b
Revises:
Create Date: 2026-09-28 09:22:29.258482
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "a3a33278ac8b"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_logs",
        sa.Column("actor_user_id", sa.Uuid(), nullable=True),
        sa.Column("action", sa.String(length=64), nullable=False),
        sa.Column("entity_type", sa.String(length=32), nullable=False),
        sa.Column("entity_id", sa.String(length=64), nullable=True),
        sa.Column("data", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_logs")),
    )
    op.create_index("ix_audit_logs_created_at", "audit_logs", ["created_at"], unique=False)
    op.create_index("ix_audit_logs_entity", "audit_logs", ["entity_type", "entity_id"], unique=False)
    op.create_table(
        "organizations",
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "approved",
                "rejected",
                "suspended",
                name="org_status",
                native_enum=False,
                create_constraint=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("country", sa.String(length=2), nullable=False),
        sa.Column("city", sa.String(length=100), nullable=True),
        sa.Column("phone", sa.String(length=32), nullable=True),
        sa.Column("logo_key", sa.String(length=300), nullable=True),
        sa.Column("settings", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "status IN ('pending', 'approved', 'rejected', 'suspended')",
            name=op.f("ck_organizations_org_status"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_organizations")),
    )
    op.create_table(
        "themes",
        sa.Column("slug", sa.String(length=64), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("title_ar", sa.String(length=200), nullable=False),
        sa.Column("title_en", sa.String(length=200), nullable=False),
        sa.Column("age_min", sa.SmallInteger(), nullable=False),
        sa.Column("age_max", sa.SmallInteger(), nullable=False),
        sa.Column("occasion", sa.String(length=64), nullable=True),
        sa.Column("is_b2b", sa.Boolean(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("companion_slot", sa.Boolean(), nullable=False),
        sa.Column("definition", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_themes")),
        sa.UniqueConstraint("slug", name=op.f("uq_themes_slug")),
    )
    op.create_table(
        "classrooms",
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("school_year", sa.String(length=16), nullable=True),
        sa.Column("teacher_name", sa.String(length=120), nullable=True),
        sa.Column("invite_token", sa.String(length=64), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_classrooms_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_classrooms")),
        sa.UniqueConstraint("invite_token", name=op.f("uq_classrooms_invite_token")),
    )
    op.create_index(op.f("ix_classrooms_organization_id"), "classrooms", ["organization_id"], unique=False)
    op.create_table(
        "print_batches",
        sa.Column("organization_id", sa.Uuid(), nullable=True),
        sa.Column("batch_date", sa.Date(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "open",
                "sent",
                "printing",
                "done",
                name="print_batch_status",
                native_enum=False,
                create_constraint=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("bundle_key", sa.String(length=300), nullable=True),
        sa.Column("printer_notified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "status IN ('open', 'sent', 'printing', 'done')", name=op.f("ck_print_batches_print_batch_status")
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_print_batches_organization_id_organizations"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_print_batches")),
    )
    op.create_index(
        op.f("ix_print_batches_organization_id"), "print_batches", ["organization_id"], unique=False
    )
    op.create_table(
        "users",
        sa.Column("email", sa.String(length=254), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=True),
        sa.Column("full_name", sa.String(length=120), nullable=False),
        sa.Column("phone", sa.String(length=32), nullable=True),
        sa.Column(
            "role",
            sa.Enum(
                "parent",
                "school_admin",
                "admin",
                name="user_role",
                native_enum=False,
                create_constraint=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "locale",
            sa.Enum("ar", "en", name="user_locale", native_enum=False, create_constraint=False, length=32),
            nullable=False,
        ),
        sa.Column("organization_id", sa.Uuid(), nullable=True),
        sa.Column("google_sub", sa.String(length=255), nullable=True),
        sa.Column("email_verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("locale IN ('ar', 'en')", name=op.f("ck_users_user_locale")),
        sa.CheckConstraint("role IN ('parent', 'school_admin', 'admin')", name=op.f("ck_users_user_role")),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_users_organization_id_organizations"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("email", name=op.f("uq_users_email")),
        sa.UniqueConstraint("google_sub", name=op.f("uq_users_google_sub")),
    )
    op.create_index(op.f("ix_users_organization_id"), "users", ["organization_id"], unique=False)
    op.create_table(
        "children",
        sa.Column("guardian_user_id", sa.Uuid(), nullable=True),
        sa.Column("organization_id", sa.Uuid(), nullable=True),
        sa.Column("classroom_id", sa.Uuid(), nullable=True),
        sa.Column("first_name", sa.String(length=40), nullable=False),
        sa.Column(
            "gender",
            sa.Enum("m", "f", name="child_gender", native_enum=False, create_constraint=False, length=32),
            nullable=False,
        ),
        sa.Column("birth_year", sa.SmallInteger(), nullable=False),
        sa.Column("interests", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("gender IN ('m', 'f')", name=op.f("ck_children_child_gender")),
        sa.ForeignKeyConstraint(
            ["classroom_id"],
            ["classrooms.id"],
            name=op.f("fk_children_classroom_id_classrooms"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["guardian_user_id"],
            ["users.id"],
            name=op.f("fk_children_guardian_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_children_organization_id_organizations"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_children")),
    )
    op.create_index(op.f("ix_children_classroom_id"), "children", ["classroom_id"], unique=False)
    op.create_index(op.f("ix_children_guardian_user_id"), "children", ["guardian_user_id"], unique=False)
    op.create_index(op.f("ix_children_organization_id"), "children", ["organization_id"], unique=False)
    op.create_table(
        "orders",
        sa.Column("code", sa.String(length=16), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column("organization_id", sa.Uuid(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "confirmed",
                "in_production",
                "shipped",
                "delivered",
                "cancelled",
                name="order_status",
                native_enum=False,
                create_constraint=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "payment_method",
            sa.Enum(
                "cod", "card", name="payment_method", native_enum=False, create_constraint=False, length=32
            ),
            nullable=False,
        ),
        sa.Column(
            "payment_status",
            sa.Enum(
                "unpaid",
                "paid",
                "refunded",
                name="payment_status",
                native_enum=False,
                create_constraint=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "currency",
            sa.Enum("ILS", "JOD", name="currency", native_enum=False, create_constraint=False, length=32),
            nullable=False,
        ),
        sa.Column("subtotal", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("delivery_fee", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("discount", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("total", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("shipping", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("print_batch_id", sa.Uuid(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("currency IN ('ILS', 'JOD')", name=op.f("ck_orders_currency")),
        sa.CheckConstraint("payment_method IN ('cod', 'card')", name=op.f("ck_orders_payment_method")),
        sa.CheckConstraint(
            "payment_status IN ('unpaid', 'paid', 'refunded')", name=op.f("ck_orders_payment_status")
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'confirmed', 'in_production', 'shipped', 'delivered', 'cancelled')",
            name=op.f("ck_orders_order_status"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_orders_organization_id_organizations"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["print_batch_id"],
            ["print_batches.id"],
            name=op.f("fk_orders_print_batch_id_print_batches"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_orders_user_id_users"), ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_orders")),
        sa.UniqueConstraint("code", name=op.f("uq_orders_code")),
    )
    op.create_index(op.f("ix_orders_organization_id"), "orders", ["organization_id"], unique=False)
    op.create_index(op.f("ix_orders_print_batch_id"), "orders", ["print_batch_id"], unique=False)
    op.create_index(op.f("ix_orders_user_id"), "orders", ["user_id"], unique=False)
    op.create_table(
        "refresh_tokens",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("family_id", sa.Uuid(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_reason", sa.String(length=16), nullable=True),
        sa.Column("user_agent", sa.String(length=300), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_refresh_tokens_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_refresh_tokens")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_refresh_tokens_token_hash")),
    )
    op.create_index(op.f("ix_refresh_tokens_family_id"), "refresh_tokens", ["family_id"], unique=False)
    op.create_index(op.f("ix_refresh_tokens_user_id"), "refresh_tokens", ["user_id"], unique=False)
    op.create_table(
        "characters",
        sa.Column("child_id", sa.Uuid(), nullable=False),
        sa.Column("art_style", sa.String(length=32), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "generating",
                "ready",
                "approved",
                "discarded",
                "failed",
                name="character_status",
                native_enum=False,
                create_constraint=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("sheet_image_key", sa.String(length=300), nullable=True),
        sa.Column("regen_count", sa.SmallInteger(), nullable=False),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("provider", sa.String(length=32), nullable=True),
        sa.Column("model", sa.String(length=100), nullable=True),
        sa.Column("params", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "status IN ('generating', 'ready', 'approved', 'discarded', 'failed')",
            name=op.f("ck_characters_character_status"),
        ),
        sa.ForeignKeyConstraint(
            ["child_id"], ["children.id"], name=op.f("fk_characters_child_id_children"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_characters")),
    )
    op.create_index(op.f("ix_characters_child_id"), "characters", ["child_id"], unique=False)
    op.create_table(
        "child_photos",
        sa.Column("child_id", sa.Uuid(), nullable=False),
        sa.Column("storage_key", sa.String(length=300), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "uploaded",
                "rejected",
                "accepted",
                "deleted",
                name="photo_status",
                native_enum=False,
                create_constraint=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("check_metrics", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("delete_after", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "status IN ('uploaded', 'rejected', 'accepted', 'deleted')",
            name=op.f("ck_child_photos_photo_status"),
        ),
        sa.ForeignKeyConstraint(
            ["child_id"], ["children.id"], name=op.f("fk_child_photos_child_id_children"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_child_photos")),
    )
    op.create_index(op.f("ix_child_photos_child_id"), "child_photos", ["child_id"], unique=False)
    op.create_index(op.f("ix_child_photos_delete_after"), "child_photos", ["delete_after"], unique=False)
    op.create_table(
        "companions",
        sa.Column("child_id", sa.Uuid(), nullable=False),
        sa.Column("book_id", sa.Uuid(), nullable=True),
        sa.Column("name", sa.String(length=30), nullable=False),
        sa.Column(
            "type_hint",
            sa.Enum(
                "creature",
                "animal",
                "robot",
                "other",
                name="companion_type",
                native_enum=False,
                create_constraint=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("type_other", sa.String(length=30), nullable=True),
        sa.Column("traits", sa.String(length=120), nullable=True),
        sa.Column("description_en", sa.Text(), nullable=True),
        sa.Column("drawing_key", sa.String(length=300), nullable=True),
        sa.Column("drawing_delete_after", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cleaned_key", sa.String(length=300), nullable=True),
        sa.Column("sheet_key", sa.String(length=300), nullable=True),
        sa.Column("regen_count", sa.SmallInteger(), nullable=False),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("provider", sa.String(length=32), nullable=True),
        sa.Column("model", sa.String(length=100), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "type_hint IN ('creature', 'animal', 'robot', 'other')", name=op.f("ck_companions_companion_type")
        ),
        sa.ForeignKeyConstraint(
            ["child_id"], ["children.id"], name=op.f("fk_companions_child_id_children"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_companions")),
    )
    op.create_index(op.f("ix_companions_child_id"), "companions", ["child_id"], unique=False)
    op.create_index(
        op.f("ix_companions_drawing_delete_after"), "companions", ["drawing_delete_after"], unique=False
    )
    op.create_table(
        "consents",
        sa.Column("child_id", sa.Uuid(), nullable=False),
        sa.Column("guardian_user_id", sa.Uuid(), nullable=False),
        sa.Column("consent_text_version", sa.String(length=32), nullable=False),
        sa.Column("scope", sa.String(length=32), nullable=False),
        sa.Column("accepted_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("ip", sa.String(length=45), nullable=True),
        sa.Column("user_agent", sa.String(length=300), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["child_id"], ["children.id"], name=op.f("fk_consents_child_id_children"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["guardian_user_id"],
            ["users.id"],
            name=op.f("fk_consents_guardian_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_consents")),
    )
    op.create_index(op.f("ix_consents_child_id"), "consents", ["child_id"], unique=False)
    op.create_table(
        "books",
        sa.Column("child_id", sa.Uuid(), nullable=False),
        sa.Column("character_id", sa.Uuid(), nullable=True),
        sa.Column("companion_id", sa.Uuid(), nullable=True),
        sa.Column("theme_id", sa.Uuid(), nullable=False),
        sa.Column("theme_version", sa.Integer(), nullable=False),
        sa.Column("created_by_user_id", sa.Uuid(), nullable=True),
        sa.Column(
            "language",
            sa.Enum("ar", "en", name="book_language", native_enum=False, create_constraint=False, length=32),
            nullable=False,
        ),
        sa.Column("art_style", sa.String(length=32), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "draft",
                "generating",
                "preview",
                "approved",
                "ordered",
                "printed",
                "failed",
                name="book_status",
                native_enum=False,
                create_constraint=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("title", sa.String(length=200), nullable=True),
        sa.Column("dedication", sa.Text(), nullable=True),
        sa.Column("pdf_interior_key", sa.String(length=300), nullable=True),
        sa.Column("pdf_cover_key", sa.String(length=300), nullable=True),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("approved_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("language IN ('ar', 'en')", name=op.f("ck_books_book_language")),
        sa.CheckConstraint(
            "status IN ('draft', 'generating', 'preview', 'approved', 'ordered', 'printed', 'failed')",
            name=op.f("ck_books_book_status"),
        ),
        sa.ForeignKeyConstraint(
            ["approved_by_user_id"],
            ["users.id"],
            name=op.f("fk_books_approved_by_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["character_id"],
            ["characters.id"],
            name=op.f("fk_books_character_id_characters"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["child_id"], ["children.id"], name=op.f("fk_books_child_id_children"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["companion_id"],
            ["companions.id"],
            name=op.f("fk_books_companion_id_companions"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
            name=op.f("fk_books_created_by_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["theme_id"], ["themes.id"], name=op.f("fk_books_theme_id_themes"), ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_books")),
    )
    op.create_index(op.f("ix_books_child_id"), "books", ["child_id"], unique=False)
    op.create_table(
        "book_pages",
        sa.Column("book_id", sa.Uuid(), nullable=False),
        sa.Column("index", sa.SmallInteger(), nullable=False),
        sa.Column("text", sa.Text(), nullable=True),
        sa.Column("original_text", sa.Text(), nullable=True),
        sa.Column("image_key", sa.String(length=300), nullable=True),
        sa.Column("print_image_key", sa.String(length=300), nullable=True),
        sa.Column("regen_count", sa.SmallInteger(), nullable=False),
        sa.Column(
            "safety_status",
            sa.Enum(
                "pending",
                "passed",
                "failed",
                "needs_review",
                name="safety_status",
                native_enum=False,
                create_constraint=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("review", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "safety_status IN ('pending', 'passed', 'failed', 'needs_review')",
            name=op.f("ck_book_pages_safety_status"),
        ),
        sa.ForeignKeyConstraint(
            ["book_id"], ["books.id"], name=op.f("fk_book_pages_book_id_books"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_book_pages")),
        sa.UniqueConstraint("book_id", "index", name=op.f("uq_book_pages_book_id_index")),
    )
    op.create_index(op.f("ix_book_pages_book_id"), "book_pages", ["book_id"], unique=False)
    op.create_table(
        "generation_costs",
        sa.Column("book_id", sa.Uuid(), nullable=True),
        sa.Column("child_id", sa.Uuid(), nullable=True),
        sa.Column("step", sa.String(length=64), nullable=False),
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.Column("model", sa.String(length=100), nullable=False),
        sa.Column("units", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("usd", sa.Numeric(precision=10, scale=5), nullable=False),
        sa.Column("estimated", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["book_id"], ["books.id"], name=op.f("fk_generation_costs_book_id_books"), ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["child_id"],
            ["children.id"],
            name=op.f("fk_generation_costs_child_id_children"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_generation_costs")),
    )
    op.create_index(op.f("ix_generation_costs_book_id"), "generation_costs", ["book_id"], unique=False)
    op.create_table(
        "order_items",
        sa.Column("order_id", sa.Uuid(), nullable=False),
        sa.Column("book_id", sa.Uuid(), nullable=True),
        sa.Column(
            "product",
            sa.Enum(
                "digital",
                "softcover",
                "hardcover",
                "class_book",
                name="product",
                native_enum=False,
                create_constraint=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("addons", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("quantity", sa.SmallInteger(), nullable=False),
        sa.Column("unit_price", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "product IN ('digital', 'softcover', 'hardcover', 'class_book')",
            name=op.f("ck_order_items_product"),
        ),
        sa.ForeignKeyConstraint(
            ["book_id"], ["books.id"], name=op.f("fk_order_items_book_id_books"), ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["order_id"], ["orders.id"], name=op.f("fk_order_items_order_id_orders"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_order_items")),
    )
    op.create_index(op.f("ix_order_items_order_id"), "order_items", ["order_id"], unique=False)
    op.create_table(
        "share_tokens",
        sa.Column("book_id", sa.Uuid(), nullable=False),
        sa.Column("token", sa.String(length=64), nullable=False),
        sa.Column(
            "scope",
            sa.Enum(
                "read",
                "listen",
                "record",
                name="share_scope",
                native_enum=False,
                create_constraint=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("label", sa.String(length=60), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("scope IN ('read', 'listen', 'record')", name=op.f("ck_share_tokens_share_scope")),
        sa.ForeignKeyConstraint(
            ["book_id"], ["books.id"], name=op.f("fk_share_tokens_book_id_books"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_share_tokens")),
        sa.UniqueConstraint("token", name=op.f("uq_share_tokens_token")),
    )
    op.create_index(op.f("ix_share_tokens_book_id"), "share_tokens", ["book_id"], unique=False)
    op.create_table(
        "recordings",
        sa.Column("book_id", sa.Uuid(), nullable=False),
        sa.Column("page_index", sa.SmallInteger(), nullable=False),
        sa.Column("voice_label", sa.String(length=30), nullable=False),
        sa.Column("storage_key", sa.String(length=300), nullable=False),
        sa.Column("duration_ms", sa.Integer(), nullable=False),
        sa.Column("created_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("created_by_share_token_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["book_id"], ["books.id"], name=op.f("fk_recordings_book_id_books"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["created_by_share_token_id"],
            ["share_tokens.id"],
            name=op.f("fk_recordings_created_by_share_token_id_share_tokens"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
            name=op.f("fk_recordings_created_by_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_recordings")),
        sa.UniqueConstraint(
            "book_id", "page_index", "voice_label", name=op.f("uq_recordings_book_id_page_index_voice_label")
        ),
    )
    op.create_index(op.f("ix_recordings_book_id"), "recordings", ["book_id"], unique=False)
    op.create_foreign_key(
        op.f("fk_companions_book_id_books"), "companions", "books", ["book_id"], ["id"], ondelete="SET NULL"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("fk_companions_book_id_books"), "companions", type_="foreignkey")
    op.drop_index(op.f("ix_recordings_book_id"), table_name="recordings")
    op.drop_table("recordings")
    op.drop_index(op.f("ix_share_tokens_book_id"), table_name="share_tokens")
    op.drop_table("share_tokens")
    op.drop_index(op.f("ix_order_items_order_id"), table_name="order_items")
    op.drop_table("order_items")
    op.drop_index(op.f("ix_generation_costs_book_id"), table_name="generation_costs")
    op.drop_table("generation_costs")
    op.drop_index(op.f("ix_book_pages_book_id"), table_name="book_pages")
    op.drop_table("book_pages")
    op.drop_index(op.f("ix_books_child_id"), table_name="books")
    op.drop_table("books")
    op.drop_index(op.f("ix_consents_child_id"), table_name="consents")
    op.drop_table("consents")
    op.drop_index(op.f("ix_companions_drawing_delete_after"), table_name="companions")
    op.drop_index(op.f("ix_companions_child_id"), table_name="companions")
    op.drop_table("companions")
    op.drop_index(op.f("ix_child_photos_delete_after"), table_name="child_photos")
    op.drop_index(op.f("ix_child_photos_child_id"), table_name="child_photos")
    op.drop_table("child_photos")
    op.drop_index(op.f("ix_characters_child_id"), table_name="characters")
    op.drop_table("characters")
    op.drop_index(op.f("ix_refresh_tokens_user_id"), table_name="refresh_tokens")
    op.drop_index(op.f("ix_refresh_tokens_family_id"), table_name="refresh_tokens")
    op.drop_table("refresh_tokens")
    op.drop_index(op.f("ix_orders_user_id"), table_name="orders")
    op.drop_index(op.f("ix_orders_print_batch_id"), table_name="orders")
    op.drop_index(op.f("ix_orders_organization_id"), table_name="orders")
    op.drop_table("orders")
    op.drop_index(op.f("ix_children_organization_id"), table_name="children")
    op.drop_index(op.f("ix_children_guardian_user_id"), table_name="children")
    op.drop_index(op.f("ix_children_classroom_id"), table_name="children")
    op.drop_table("children")
    op.drop_index(op.f("ix_users_organization_id"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_print_batches_organization_id"), table_name="print_batches")
    op.drop_table("print_batches")
    op.drop_index(op.f("ix_classrooms_organization_id"), table_name="classrooms")
    op.drop_table("classrooms")
    op.drop_table("themes")
    op.drop_table("organizations")
    op.drop_index("ix_audit_logs_entity", table_name="audit_logs")
    op.drop_index("ix_audit_logs_created_at", table_name="audit_logs")
    op.drop_table("audit_logs")
    # ### end Alembic commands ###
